# Generated by Django 2.2.13 on 2021-07-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_auto_20210630_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(blank=True, default='images/no_imagen.png', null=True, upload_to='images/'),
        ),
    ]
