# Generated by Django 2.2.13 on 2021-06-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_historialpreciosventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barra',
            field=models.CharField(auto_created=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(blank=True, default='image/no_imagen.png', null=True, upload_to='images/'),
        ),
    ]
