# Generated by Django 2.2.13 on 2021-07-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='casa',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
