# Generated by Django 2.2.13 on 2021-07-02 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inv', '0004_auto_20210701_0014'),
        ('fac', '0002_cliente_casa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.FloatField(default=1)),
                ('cantidad', models.IntegerField(default=1)),
                ('total', models.FloatField()),
                ('plazo', models.DateField(blank=True, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fac.Cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inv.Producto')),
            ],
            options={
                'verbose_name': 'Presupuestos',
                'verbose_name_plural': 'Presupuestos',
            },
        ),
    ]
