# Generated by Django 2.2.13 on 2021-07-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
