# Generated by Django 2.2.13 on 2021-06-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domicilios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Domicilio',
        ),
    ]
